USGS-R/geoknife

R/initializeProcessInputs.R
R/processInputsToXML.R
R/setFeature.R
R/startProcess.R
inst/extdata/multi_poly_post.xml
man/startProcess.Rd

simple feature linearRings

---

DESCRIPTION
R/processInputsToXML.R

minor update w/ named simple features

---

README.md

updated to v0.4.1

---

R/02-webgeom-obj.R
R/bufferPoint.R
R/processInputsToXML.R
R/start-geojob.R
R/successful.R
R/values-webgeom.R
README.md
man/XML-method.Rd
man/bufferPoint.Rd
man/start-methods.Rd
man/webgeom-methods.Rd
tests/testthat/test-setJobState.R
tests/testthat/test-waitUntilFinished.R

fixes for multiple open issues

---

DESCRIPTION
R/email-geojob.R
R/show-geojob.R
R/show-simplegeom.R
R/show-webdata.R
R/show-webgeom.R

show methods for objects

---

DESCRIPTION
R/01-webdata-obj.R
R/geoknife-generic.R
R/show-webgeom.R
R/start-geojob.R
man/geoknife-methods.Rd
man/start-methods.Rd
man/webdata-methods.Rd
tests/testthat/test-geoknife_xml_parser.R
tests/testthat/test-setJobState.R

fix for process state bug

---

R/query-webgeom.R
R/times-webdata.R
R/variables-webdata.R
README.md
man/variables-webdata.Rd
vignettes/geoknife.Rmd
vignettes/geoknife.html

updating vignette

---

DESCRIPTION
R/parseTimeseries.R

factors showed up in `loadOutput`. This is a fix for it.

fix for #168

---

DESCRIPTION
R/04-webprocess-obj.R
R/inputs-webprocess.R

setting additional inputs on initialize

---

DESCRIPTION
LICENSE
R/04-webprocess-obj.R
R/download-geojob.R
man/webprocess-methods.Rd
tests/testthat/test-webprocess_object.R

pass through of wp

---

DESCRIPTION
R/check.R
R/successful.R
R/waitUntilFinished.R
man/successful-methods.Rd
man/webprocess-methods.Rd

#70 
added a retry for `waitUntilFinished` and `running`

using retry on waitUntilFinished

---

R/url-generic.R
man/url.Rd
tests/testthat/test-query_webdatasets.R

the rest of #191 (url())

---

R/04-webprocess-obj.R
tests/testthat/test-webprocess_input.R
tests/testthat/test-webprocess_object.R

Knife init

---

DESCRIPTION
R/query-webgeom.R
R/values-webgeom.R

fixes #289 
@dblodgett-usgs can you take a quick look? Just adding a small bit to the xpath

fix for value filtering bug report

---

DESCRIPTION
R/values-webgeom.R
tests/testthat/test-geoknife_setters.R

values() error message

---

DESCRIPTION
R/02-webgeom-obj.R
R/values-webgeom.R
man/webgeom-methods.Rd

slightly faster for #312 and fix docs for #310

update example 

---

R/01-webdata-obj.R
R/03-geojob-obj.R
man/webdata-methods.Rd
tests/testthat/test-webdata_object.R

webdata from geojob

---

R/01-webdata-obj.R
tests/testthat/test-webdata_object.R

change how times are handled in geojob -> webdata

---

DESCRIPTION
R/00-gconfig.R
R/01-webdata-obj.R
R/06-simplegeom-obj.R
R/07-datagroup-obj.R
R/geoknife-generic.R
R/geom-webgeom.R
R/query-webdata-variables.R
R/setJobState.R
cran-comments.md
man/datagroup-class.Rd
man/gconfig.Rd
man/geoknife-methods.Rd
man/geom.Rd
man/getJobState.Rd
man/simplegeom-class.Rd
man/variables_query-method.Rd
man/webdata-class.Rd

CRAN release, typos

---

.Rbuildignore
.gitignore
DESCRIPTION

@jread-usgs don't merge until CRAN build passes

.Rbuildignore for CRAN

---

R/check.R
tests/testthat/test-geoknife_utils.R

add percent complete for check ()

---

DESCRIPTION

Didn't do this with the url update

bump date and version before cutting release

---

inst/doc/custom_data_sources.R
inst/doc/custom_data_sources.Rmd
inst/doc/custom_data_sources.html
inst/doc/geoknife.Rmd
inst/doc/geoknife.html
inst/doc/plot_geotiff.R
inst/doc/plot_geotiff.Rmd
inst/doc/plot_geotiff.html
vignettes/custom_data_sources.Rmd
vignettes/geoknife.Rmd

Still wasn't passing win-builder

more vignette fixes for CRAN 

---

R/06-simplegeom-obj.R
inst/draw.xsd
inst/extdata/multi_poly_post.xml
inst/extdata/testjob.xml
tests/testthat/data/test_XML_sg_xml.xml
tests/testthat/data/test_XML_two_points_xml.xml

I reverse engineered the old draw.xsd and got this working in it's current form. It will need t be merged in order for the fix to work. We hsould work on a better long term home for this file -- I'm just not sure what that home should be at this point.

temporary fixed draw.xsd solution

---

README.Rmd
README.md

@lindsayplatt is tweeting about this, so wanted to get the version updated in the readme title.  Maybe ideally the readme build could be baked into the package build command?  I'm rusty on package build stuff.

rebuild readme

---

.github/workflows/R-CMD-check.yml
DESCRIPTION
NEWS.md
R/06-simplegeom-obj.R
R/processInputsToXML.R
tests/testthat/data/test_XML_sg_xml.xml
tests/testthat/test-geoknife_setters.R

``` r
library(geoknife)
#> 
#> Attaching package: 'geoknife'
#> The following object is masked from 'package:stats':
#> 
#>     start
#> The following object is masked from 'package:graphics':
#> 
#>     title
#> The following object is masked from 'package:base':
#> 
#>     url
library(sf)
#> Linking to GEOS 3.9.1, GDAL 3.2.1, PROJ 7.2.1; sf_use_s2() is TRUE
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following object is masked from 'package:geoknife':
#> 
#>     id
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
query_simplegeom <- st_as_sf(maps::map("county", c("minnesota,washington","minnesota,hennepin"), fill=T, plot=F)) %>% …
```

fixes #409

---

inst/extdata/draw.xsd

adding this here as a temporary solution -- it will be part of the official code.usgs.gov repository when we get that going.

add draw.xsd
